spring:
  application:
    name: rideshare_app
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:${MONGODB_URI}}

server:
  port: ${SERVER_PORT:8081}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
